name: payu_web_payments
description: Flutter package which allows to make Web payments via Payu
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_api:
    git:
      url: https://github.com/Domson12/PayU-Flutter-plus
      path: payu_api
  payu_core:
    git:
      url: https://github.com/Domson12/PayU-Flutter-plus
      path: payu_core
  payu_state_management:
    git:
      url: https://github.com/Domson12/PayU-Flutter-plus
      path: payu_state_management
  payu_translations:
    git:
      url: https://github.com/Domson12/PayU-Flutter-plus
      path: payu_translations
  payu_ui:
    git:
      url: hhttps://github.com/Domson12/PayU-Flutter-plus
      path: payu_ui
  webview_flutter: ^3.0.4
dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  http: ^1.2.1
  mockito: ^5.3.2
flutter:
