name: payu_ui
description: Flutter package with Payu UI elements.
version: 1.0.2
publish_to: none
homepage: https://github.com/Domson12/PayU-Flutter-plus
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  payu_interface:
    git:
      url: https://github.com/Domson12/PayU-Flutter-plus
      path: payu_interface
  provider: ^6.0.3
dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1
flutter:
